# AUTOGENERATED! DO NOT EDIT! File to edit: ../02_sub.core.ipynb.

# %% auto 0
__all__ = ['foo']

# %% ../02_sub.core.ipynb 2
from ... import utils

# %% ../02_sub.core.ipynb 3
def foo():
    print("sub core foo")
